# Generated by Django 4.1.1 on 2022-09-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histo',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
