# Generated by Django 4.1.1 on 2022-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='content',
            field=models.CharField(max_length=999999),
        ),
    ]
